/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package graphic;

import java.awt.BorderLayout;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import hamming_pack.*;

/**
 *
 * @author luciana
 */
public class Principal extends java.awt.Frame {

    private static Principal principal;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        inicio.setVisible(true);
    }
    
    public static Principal getPrincipal(){
        return principal;
    }
    
    public JPanel getHamming(){
        return hamming;
    }
    
    public JPanel getInicio(){
        return inicio;
    }
    
    
    
     // go_to es una funcion que nos ayuda a cambiar entre los paneles del sistema
    public void go_to(JPanel panel) {
        ventana.removeAll();
        ventana.add(panel,BorderLayout.CENTER);
        ventana.repaint();
        ventana.revalidate();
    }
    
    public void PopUp(String Imprimir, String imagen, String titulo) {
        Icon ip = new javax.swing.ImageIcon(getClass().getResource(imagen));

        JLabel jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 17));
        jLabel9.setText(Imprimir);

        JOptionPane.showMessageDialog(this, jLabel9,
            " "+ titulo, JOptionPane.PLAIN_MESSAGE, ip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        b_huffman = new javax.swing.JButton();
        b_hamming = new javax.swing.JButton();
        apellidos = new javax.swing.JLabel();
        Teoria_info = new javax.swing.JLabel();
        hamming = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cargar_arc = new javax.swing.JButton();
        proteger = new javax.swing.JButton();
        error = new javax.swing.JButton();
        decodificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        ventana.setBackground(new java.awt.Color(20, 13, 54));
        ventana.setPreferredSize(new java.awt.Dimension(1300, 750));
        ventana.setLayout(new javax.swing.BoxLayout(ventana, javax.swing.BoxLayout.LINE_AXIS));

        inicio.setBackground(new java.awt.Color(20, 13, 54));
        inicio.setMinimumSize(new java.awt.Dimension(1300, 750));
        inicio.setPreferredSize(new java.awt.Dimension(1300, 750));
        inicio.setLayout(null);

        b_huffman.setBackground(new java.awt.Color(44, 32, 106));
        b_huffman.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        b_huffman.setForeground(new java.awt.Color(241, 240, 255));
        b_huffman.setText("HUFFMAN");
        b_huffman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b_huffman.setBorderPainted(false);
        b_huffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_huffmanActionPerformed(evt);
            }
        });
        inicio.add(b_huffman);
        b_huffman.setBounds(660, 370, 190, 50);

        b_hamming.setBackground(new java.awt.Color(44, 32, 106));
        b_hamming.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        b_hamming.setForeground(new java.awt.Color(241, 240, 255));
        b_hamming.setText("HAMMING");
        b_hamming.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 32, 106), 9, true));
        b_hamming.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_hamming.setOpaque(true);
        b_hamming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hammingActionPerformed(evt);
            }
        });
        inicio.add(b_hamming);
        b_hamming.setBounds(390, 370, 190, 50);

        apellidos.setFont(new java.awt.Font("URW Gothic L", 1, 30)); // NOI18N
        apellidos.setForeground(new java.awt.Color(241, 240, 255));
        apellidos.setText("BROCAS Y LOYOLA");
        inicio.add(apellidos);
        apellidos.setBounds(480, 170, 280, 50);

        Teoria_info.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        Teoria_info.setForeground(new java.awt.Color(241, 240, 255));
        Teoria_info.setText("TEORIA DE LA INFORMACION");
        inicio.add(Teoria_info);
        Teoria_info.setBounds(380, 110, 500, 50);

        ventana.add(inicio);

        hamming.setBackground(new java.awt.Color(20, 13, 54));
        hamming.setPreferredSize(new java.awt.Dimension(1300, 750));
        hamming.setLayout(null);

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 240, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HAMMING");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 32, 106), 2, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        hamming.add(jLabel1);
        jLabel1.setBounds(490, 100, 250, 70);

        cargar_arc.setBackground(new java.awt.Color(44, 32, 106));
        cargar_arc.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        cargar_arc.setForeground(new java.awt.Color(241, 240, 255));
        cargar_arc.setText("CARGAR ARCHIVO");
        cargar_arc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cargar_arc.setBorderPainted(false);
        cargar_arc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_arcActionPerformed(evt);
            }
        });
        hamming.add(cargar_arc);
        cargar_arc.setBounds(220, 240, 310, 70);

        proteger.setBackground(new java.awt.Color(44, 32, 106));
        proteger.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        proteger.setForeground(new java.awt.Color(241, 240, 255));
        proteger.setText("PROTEGER ARCHIVO");
        proteger.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        proteger.setBorderPainted(false);
        proteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerActionPerformed(evt);
            }
        });
        hamming.add(proteger);
        proteger.setBounds(700, 240, 310, 70);

        error.setBackground(new java.awt.Color(44, 32, 106));
        error.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        error.setForeground(new java.awt.Color(241, 240, 255));
        error.setText("INTRODUCIR ERRORES");
        error.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        error.setBorderPainted(false);
        error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorActionPerformed(evt);
            }
        });
        hamming.add(error);
        error.setBounds(220, 390, 310, 70);

        decodificar.setBackground(new java.awt.Color(44, 32, 106));
        decodificar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        decodificar.setForeground(new java.awt.Color(241, 240, 255));
        decodificar.setText("DESPROTEGER ARCHIVO");
        decodificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        decodificar.setBorderPainted(false);
        decodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodificarActionPerformed(evt);
            }
        });
        hamming.add(decodificar);
        decodificar.setBounds(700, 390, 310, 70);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 32, 106), 2));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        hamming.add(jLabel3);
        jLabel3.setBounds(30, 30, 50, 50);

        ventana.add(hamming);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void b_huffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_huffmanActionPerformed
        PopUp("¡En construccion! Vuelva pronto :)", "/iconos/construccion.png", "Ups");
    }//GEN-LAST:event_b_huffmanActionPerformed

    private void b_hammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hammingActionPerformed
        go_to(hamming);
    }//GEN-LAST:event_b_hammingActionPerformed

    private void cargar_arcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_arcActionPerformed
        go_to(new cargar_archivo());
    }//GEN-LAST:event_cargar_arcActionPerformed

    private void protegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerActionPerformed
        go_to(new codificar());
    }//GEN-LAST:event_protegerActionPerformed

    private void errorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorActionPerformed
        go_to(new intro_error());
    }//GEN-LAST:event_errorActionPerformed

    private void decodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decodificarActionPerformed
        go_to(new decodificar());
    }//GEN-LAST:event_decodificarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        go_to(inicio);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                    principal = new Principal();
                    principal.setLocationRelativeTo(null);
                    principal.setVisible(true);
                    principal.setTitle("Trabajo Integrador");
                    principal.setResizable(false);
                    
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Teoria_info;
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton b_hamming;
    private javax.swing.JButton b_huffman;
    private javax.swing.JButton cargar_arc;
    private javax.swing.JButton decodificar;
    private javax.swing.JButton error;
    private javax.swing.JPanel hamming;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton proteger;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}
