/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hamming_pack;

import graphic.*;

/**
 *
 * @author luciana
 */
public class cargar_archivo extends javax.swing.JPanel {

    /**
     * Creates new form cargar_archivo
     */
    public cargar_archivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hamming = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        confirmar2 = new javax.swing.JButton();

        hamming.setBackground(new java.awt.Color(20, 13, 54));
        hamming.setPreferredSize(new java.awt.Dimension(1300, 750));
        hamming.setLayout(null);

        titulo.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(241, 240, 255));
        titulo.setText("CARGAR ARCHIVO");
        hamming.add(titulo);
        titulo.setBounds(490, 70, 330, 50);

        confirmar.setBackground(new java.awt.Color(44, 32, 106));
        confirmar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar.setForeground(new java.awt.Color(241, 240, 255));
        confirmar.setText("EXTRAER");
        confirmar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar.setBorderPainted(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        hamming.add(confirmar);
        confirmar.setBounds(550, 160, 200, 60);

        cancelar.setBackground(new java.awt.Color(44, 32, 106));
        cancelar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(241, 240, 255));
        cancelar.setText("CANCELAR");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.setBorderPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        hamming.add(cancelar);
        cancelar.setBounds(70, 610, 200, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        hamming.add(jScrollPane1);
        jScrollPane1.setBounds(320, 260, 670, 410);

        confirmar2.setBackground(new java.awt.Color(44, 32, 106));
        confirmar2.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar2.setForeground(new java.awt.Color(241, 240, 255));
        confirmar2.setText("CONFIRMAR");
        confirmar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar2.setBorderPainted(false);
        confirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar2ActionPerformed(evt);
            }
        });
        hamming.add(confirmar2);
        confirmar2.setBounds(1040, 610, 200, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(hamming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(hamming, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        graphic.Principal.getPrincipal().go_to(graphic.Principal.getPrincipal().getHamming());
    }//GEN-LAST:event_cancelarActionPerformed

    private void confirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton confirmar2;
    private javax.swing.JPanel hamming;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
