/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hamming_pack;

/**
 *
 * @author luciana
 */
public class decodificar extends javax.swing.JPanel {

    /**
     * Creates new form decodificar
     */
    public decodificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        resultado = new javax.swing.JPanel();
        confirmar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        titulo2 = new javax.swing.JLabel();
        antes = new javax.swing.JLabel();
        despues = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 750));
        setLayout(null);

        previo.setBackground(new java.awt.Color(20, 13, 54));
        previo.setPreferredSize(new java.awt.Dimension(1300, 750));
        previo.setLayout(null);

        titulo.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(241, 240, 255));
        titulo.setText("DECODIFICAR");
        previo.add(titulo);
        titulo.setBounds(550, 110, 250, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        previo.add(jComboBox1);
        jComboBox1.setBounds(370, 250, 290, 40);

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 240, 255));
        jLabel1.setText("CORREGIR:");
        previo.add(jLabel1);
        jLabel1.setBounds(220, 340, 140, 40);

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 240, 255));
        jLabel2.setText("ARCHIVO: ");
        previo.add(jLabel2);
        jLabel2.setBounds(220, 240, 140, 40);

        jCheckBox1.setPreferredSize(new java.awt.Dimension(25, 25));
        previo.add(jCheckBox1);
        jCheckBox1.setBounds(370, 350, 25, 25);

        confirmar.setBackground(new java.awt.Color(44, 32, 106));
        confirmar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar.setForeground(new java.awt.Color(241, 240, 255));
        confirmar.setText("CONFIRMAR");
        confirmar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar.setBorderPainted(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        previo.add(confirmar);
        confirmar.setBounds(1010, 610, 200, 60);

        cancelar.setBackground(new java.awt.Color(44, 32, 106));
        cancelar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(241, 240, 255));
        cancelar.setText("CANCELAR");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.setBorderPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        previo.add(cancelar);
        cancelar.setBounds(80, 610, 200, 60);

        add(previo);
        previo.setBounds(0, 0, 1300, 750);

        resultado.setBackground(new java.awt.Color(20, 13, 54));
        resultado.setPreferredSize(new java.awt.Dimension(1300, 750));
        resultado.setLayout(null);

        confirmar1.setBackground(new java.awt.Color(44, 32, 106));
        confirmar1.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar1.setForeground(new java.awt.Color(241, 240, 255));
        confirmar1.setText("CONFIRMAR");
        confirmar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar1.setBorderPainted(false);
        confirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar1ActionPerformed(evt);
            }
        });
        resultado.add(confirmar1);
        confirmar1.setBounds(1050, 640, 200, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        resultado.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 590, 460);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        resultado.add(jScrollPane2);
        jScrollPane2.setBounds(660, 160, 590, 460);

        titulo2.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(241, 240, 255));
        titulo2.setText("ARCHIVO FINAL");
        resultado.add(titulo2);
        titulo2.setBounds(520, 30, 280, 50);

        antes.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        antes.setForeground(new java.awt.Color(241, 240, 255));
        antes.setText("ARCHIVO CODIFICADO");
        resultado.add(antes);
        antes.setBounds(40, 110, 280, 50);

        despues.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        despues.setForeground(new java.awt.Color(241, 240, 255));
        despues.setText("ARCHIVO DECODIFICADO");
        resultado.add(despues);
        despues.setBounds(660, 110, 310, 50);

        add(resultado);
        resultado.setBounds(0, 0, 1300, 750);

        getAccessibleContext().setAccessibleName("1300");
        getAccessibleContext().setAccessibleDescription("750");
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarActionPerformed

    private void confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmar1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        graphic.Principal.getPrincipal().go_to(graphic.Principal.getPrincipal().getHamming());
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antes;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton confirmar1;
    private javax.swing.JLabel despues;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel previo;
    private javax.swing.JPanel resultado;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
