/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hamming_pack;

/**
 *
 * @author luciana
 */
public class intro_error extends javax.swing.JPanel {

    /**
     * Creates new form intro_error
     */
    public intro_error() {
        initComponents();
        resultado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hamming = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        resultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        titulo2 = new javax.swing.JLabel();
        antes = new javax.swing.JLabel();
        despues = new javax.swing.JLabel();
        confirmar2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1300, 750));
        setLayout(null);

        hamming.setBackground(new java.awt.Color(20, 13, 54));
        hamming.setPreferredSize(new java.awt.Dimension(1300, 750));
        hamming.setLayout(null);

        titulo.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(241, 240, 255));
        titulo.setText("INTRODUCIR ERROR");
        hamming.add(titulo);
        titulo.setBounds(520, 110, 350, 50);

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 240, 255));
        jLabel1.setText("SELECCIONE EL ARCHIVO AL QUE DESEA INTRODUCIR ERRORES:");
        hamming.add(jLabel1);
        jLabel1.setBounds(30, 200, 730, 40);

        confirmar.setBackground(new java.awt.Color(44, 32, 106));
        confirmar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar.setForeground(new java.awt.Color(241, 240, 255));
        confirmar.setText("CONFIRMAR");
        confirmar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar.setBorderPainted(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        hamming.add(confirmar);
        confirmar.setBounds(1060, 650, 200, 60);

        cancelar.setBackground(new java.awt.Color(44, 32, 106));
        cancelar.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(241, 240, 255));
        cancelar.setText("CANCELAR");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.setBorderPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        hamming.add(cancelar);
        cancelar.setBounds(40, 640, 200, 60);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        hamming.add(jScrollPane3);
        jScrollPane3.setBounds(340, 250, 620, 320);

        add(hamming);
        hamming.setBounds(0, 0, 1300, 750);

        resultado.setBackground(new java.awt.Color(20, 13, 54));
        resultado.setPreferredSize(new java.awt.Dimension(1300, 750));
        resultado.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        resultado.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 590, 460);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        resultado.add(jScrollPane2);
        jScrollPane2.setBounds(660, 160, 590, 460);

        titulo2.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(241, 240, 255));
        titulo2.setText("ARCHIVO FINAL");
        resultado.add(titulo2);
        titulo2.setBounds(520, 30, 280, 50);

        antes.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        antes.setForeground(new java.awt.Color(241, 240, 255));
        antes.setText("ARCHIVO CODIFICADO SIN ERROR");
        resultado.add(antes);
        antes.setBounds(40, 110, 410, 50);

        despues.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        despues.setForeground(new java.awt.Color(241, 240, 255));
        despues.setText("ARCHIVO CODIFICADO CON ERROR");
        resultado.add(despues);
        despues.setBounds(660, 110, 420, 50);

        confirmar2.setBackground(new java.awt.Color(44, 32, 106));
        confirmar2.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        confirmar2.setForeground(new java.awt.Color(241, 240, 255));
        confirmar2.setText("CONFIRMAR");
        confirmar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmar2.setBorderPainted(false);
        confirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar2ActionPerformed(evt);
            }
        });
        resultado.add(confirmar2);
        confirmar2.setBounds(1050, 640, 200, 60);

        add(resultado);
        resultado.setBounds(0, 10, 647, 722);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        graphic.Principal.getPrincipal().go_to(graphic.Principal.getPrincipal().getHamming());
    }//GEN-LAST:event_cancelarActionPerformed

    private void confirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antes;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton confirmar2;
    private javax.swing.JLabel despues;
    private javax.swing.JPanel hamming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel resultado;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
