import { ScrollView , ListView, Button } from "std-widgets.slint";
import { State } from "../state.slint";

export component ShowFile inherits Rectangle {
    in property <[string]> file_text;

    in property <int> option;

    border-color: lightgray;
    border-width: 1.5px;

    width: 1200px;
    height: 400px;

    VerticalLayout {
        HorizontalLayout {
        ListView { 
            for data in [
                {text : file-text},
            ] : VerticalLayout {
                Text {
                    text: file-text[0];
                    wrap: word-wrap;
                    font-size: 14px; 
                }
            }
        }
    }
}
}
