import { Button } from "std-widgets.slint";
import { ShowFile } from "../files/show_file.slint";

export component OpButton inherits Button {
    width: 150px;
    height: 30px;
}

export component comp inherits Rectangle{
    in-out property <[string]> file-text;
    in-out property <[string]> proc-text;
    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            alignment: center;
            padding: 10px;
            t:=Text{
                text: "ORIGINAL";
                font-size: 16px;
            }
        }
        HorizontalLayout {
            alignment: center;
            ShowFile {
                file-text: file-text;
            }
        }
        HorizontalLayout {
            padding: 10px;
            alignment: center;
            p:=Text{
                padding-top: 15px;
                text: "PROCESADO";
                font-size: 16px;
            }
        }
        HorizontalLayout {
            alignment: center;
            ShowFile {
                file-text: proc-text;
            }
        }
    }
}
