import { Button } from "std-widgets.slint";
import { ShowFile } from "../files/show_file.slint";

export component OpButton inherits Button {
    width: 150px;
    height: 30px;
}

export component comp inherits Rectangle{
    in-out property <[string]> file-text;
    in-out property <[string]> proc-text;

    VerticalLayout {
        spacing: 0px;
        t:=Text{
            text: "ORIGINAL";
            font-size: 16px;
        }
        ShowFile {
            option: 0;
            file-text: file-text;
        }
        p:=Text{
            text: "PROCESADO";
            font-size: 16px;
        }
        ShowFile {
            option: 1;
            file-text: proc-text;
        }
    }
}
