import { ComboBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Decompress inherits Rectangle{
    in-out property <string> error: "";
    
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "DESCOMPRIMIR";
            font-size: 18px;
        }
    }
    HorizontalLayout{
        alignment: center;
        padding-top: 70px;
        b:=OpButton {
            text: "Elegir Archivo";
            clicked => { State.decompress()}
        }

        if error!="": VerticalLayout{
            padding-top: 10px;
            Text{
                text: error;
            } 
        }
    }  
    
     
}
