import { ComboBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Decompress inherits Rectangle{
    height: 100%;
    width: 100%;
    in-out property <[string]> proc-text;
    in-out property <[string]> file-text;
    HorizontalLayout {
        padding: 15px;
        Text {
            horizontal-alignment: center;
            text: "Descomprimir";
            font-size: 18px;
        }
    }
    HorizontalLayout{
        alignment: center;
        padding-top: 50px;
        OpButton {
            text: "Elegir Archivo";
            clicked => { State.decompress() }
        }
    }
    VerticalLayout {
        padding-top: 80px;
        padding-bottom: 15px;
        padding-left: 15px;
        padding-right: 15px;
        comp{
            file-text: file-text;
            proc-text: proc-text;
        }
    }    
}
