import { ComboBox, CheckBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Desprotect inherits Rectangle{
    in-out property <string> error;
    in-out property <[bool]> inProgress;
    HorizontalLayout {
        padding-top: 15px;
        Text {
            horizontal-alignment: center;
            text: "DESPROTEGER";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        padding-top: 50px;
        VerticalLayout {
            correct := CheckBox { 
                text: "  Corrección ";
                checked: State.correct;
                toggled => {
                    State.correct = !State.correct
                }
            }
        }
        VerticalLayout {
            b:=OpButton {
                text: "Elegir Archivo";
                clicked => { State.desprotect(State.correct) }
            }
            if error!="": VerticalLayout{
                padding-top: 10px;
                Text{
                    text: error;
                } 
            }
        }
    }
        
}
