import { ComboBox } from "std-widgets.slint";
import { comp, OpButton } from "common.slint";
import { State } from "../state.slint";

export component Protect inherits Rectangle{
    in-out property <string> error;
    in-out property <[bool]> inProgress;
    HorizontalLayout {
        padding: 15px;
        Text {
            padding-top: 10px;
            horizontal-alignment: center;
            text: "PROTEGER";
            font-size: 18px;
        }
    }
    HorizontalLayout {
        alignment: center;
        spacing: 15px;
        padding-top: 50px;
        VerticalLayout {
            alignment: center;
            Text {
                horizontal-alignment: center;
                text: "  Tamaño de bloque: ";
            }
        }
        
        combo-box := ComboBox {
            width: 100px;
            height: 30px;
            current-value: State.block-size;
            model: ["32", "2048", "65536"];
            selected => {
                State.block-size = self.current-value;
            }
        }
        b:=OpButton {
            text: "Elegir Archivo";
            
            clicked => { State.protect(combo-box.current-value);}
        }
        if error!="": VerticalLayout{
            padding-top: 10px;
            Text{
                    text: error;
                } 
        }
    }
}
