import { Compare } from "./files/compare.slint";
import { Statistics } from "./operations/statistics.slint";
import { Hamming } from "hamming.slint";
import { Huffman } from "huffman.slint";
import { HuffmanStats, HammingStats, HuffmanEntry } from "./operations/statistics.slint";
import { State } from "state.slint";
import { Button , TabWidget} from "std-widgets.slint";
import { Principal } from "principal.slint";
import { MenuBar } from "menu.slint";
export { State }

component MainWindow inherits Window {
    title: "Teoria de la Informacion";
    in-out property <[string]> errors : ["", "", "", "", ""];
    in-out property <[bool]> inProgress : [false, false, false, false, false];

    in-out property <[string]> orig-text;
    in-out property <[string]> proc-text;

    in-out property <[string]> stat : [""];
    in-out property <[HammingStats]> hamming-stats;
    in-out property <[HuffmanStats]> huffman-stats;
    in-out property <[HuffmanEntry]> huffman-table;

    in-out property <string> active-tab : "Pantalla Principal";

    min-height: 1000px;
    min-width: 1200px;

    padding: 0;
    VerticalLayout {
        spacing: 0;
        HorizontalLayout {
            spacing: 5px;
            width: 100%;
            height: 100%;

            MenuBar {
                pantalla <=> active-tab;
            }
            HorizontalLayout {
                spacing: 6px;

                if active-tab == "Pantalla Principal" : Principal {}

                if active-tab == "Hamming" : Hamming {
                    errors: errors;
                    inProgress: inProgress;
                }
                if active-tab == "Huffman" : Huffman {
                    errors: errors;
                    inProgress: inProgress;
                }
                if active-tab == "Comparar" : Compare {
                    file-text: orig-text;
                    proc-text: proc-text;

                }
                if active-tab == "stats" : Statistics {
                    stat : stat[0];
                    hamming-stats : hamming-stats[0];
                    huffman-stats : huffman-stats[0];
                    huffman-table : huffman-table;
                }
            }
        }
    }
}
